'use client';

import { useState, useEffect, useRef } from 'react';
import { 
  X, 
  Save, 
  Copy, 
  RefreshCw, 
  FileText, 
  Send,
  AlertCircle,
  CheckCircle,
  Clock
} from 'lucide-react';

interface OfferLetterEmailEditorProps {
  isOpen: boolean;
  onClose: () => void;
  applicationId: number;
  initialEmailDraft?: string;
  onSave: (emailContent: string) => Promise<void>;
  onGenerate: () => Promise<string>;
  isGenerating?: boolean;
  isSaving?: boolean;
  saveButtonLabel?: string;
  autoGenerateOnOpen?: boolean;
}

export default function OfferLetterEmailEditor({
  isOpen,
  onClose,
  applicationId,
  initialEmailDraft = '',
  onSave,
  onGenerate,
  isGenerating = false,
  isSaving = false,
  saveButtonLabel = 'Save Draft',
  autoGenerateOnOpen = true
}: OfferLetterEmailEditorProps) {
  const [emailContent, setEmailContent] = useState(initialEmailDraft);
  const [wordCount, setWordCount] = useState(0);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [error, setError] = useState('');
  const [localGenerating, setLocalGenerating] = useState(false);
  const [typingInProgress, setTypingInProgress] = useState(false);
  const typingTimerRef = useRef<NodeJS.Timeout | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    setEmailContent(initialEmailDraft);
    setHasUnsavedChanges(false);
  }, [initialEmailDraft]);

  useEffect(() => {
    const words = emailContent.trim().split(/\s+/).filter(word => word.length > 0);
    setWordCount(words.length);
  }, [emailContent]);

  useEffect(() => {
    setHasUnsavedChanges(emailContent !== initialEmailDraft);
  }, [emailContent, initialEmailDraft]);

  // Auto-generate on open with a typewriter/buffering effect
  useEffect(() => {
    const shouldAutoGenerate = isOpen && autoGenerateOnOpen && !initialEmailDraft?.trim();
    if (!shouldAutoGenerate) return;

    // Prevent double invocation (e.g., React StrictMode) and duplicate calls
    if (hasAutoGeneratedRef.current || localGenerating || isGenerating) return;
    hasAutoGeneratedRef.current = true;

    let cancelled = false;
    const run = async () => {
      try {
        setError('');
        setLocalGenerating(true);
        setTypingInProgress(true);
        const fullDraft = await onGenerate();
        if (cancelled) return;
        // Typewriter effect
        const chunkSize = 4; // characters per tick
        const intervalMs = 12; // speed
        let i = 0;
        setEmailContent('');
        if (typingTimerRef.current) clearInterval(typingTimerRef.current);
        typingTimerRef.current = setInterval(() => {
          if (cancelled) {
            if (typingTimerRef.current) clearInterval(typingTimerRef.current);
            return;
          }
          const next = fullDraft.slice(0, Math.min(i + chunkSize, fullDraft.length));
          setEmailContent(next);
          i += chunkSize;
          if (i >= fullDraft.length) {
            if (typingTimerRef.current) clearInterval(typingTimerRef.current);
            setTypingInProgress(false);
          }
        }, intervalMs);
        setHasUnsavedChanges(true);
      } catch (err: any) {
        setError(err?.message || 'Failed to generate email');
        setTypingInProgress(false);
      } finally {
        setLocalGenerating(false);
      }
    };

    run();
    return () => {
      cancelled = true;
      if (typingTimerRef.current) clearInterval(typingTimerRef.current);
      setTypingInProgress(false);
      setLocalGenerating(false);
      hasAutoGeneratedRef.current = false;
    };
  }, [isOpen, autoGenerateOnOpen, initialEmailDraft, onGenerate, localGenerating, isGenerating]);

  const handleEmailChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEmailContent(e.target.value);
    setError('');
  };

  const handleSave = async () => {
    if (!emailContent.trim()) {
      setError('Email content cannot be empty');
      return;
    }

    try {
      await onSave(emailContent);
      setHasUnsavedChanges(false);
      setError('');
    } catch (err: any) {
      setError(err.message || 'Failed to save email draft');
    }
  };

  const handleGenerate = async () => {
    try {
      setError('');
      const generatedEmail = await onGenerate();
      setEmailContent(generatedEmail);
      setHasUnsavedChanges(true);
    } catch (err: any) {
      setError(err.message || 'Failed to generate email');
    }
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(emailContent);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      setError('Failed to copy to clipboard');
    }
  };

  const handleClose = () => {
    if (hasUnsavedChanges) {
      const confirmClose = window.confirm(
        'You have unsaved changes. Are you sure you want to close without saving?'
      );
      if (!confirmClose) return;
    }
    if (typingTimerRef.current) clearInterval(typingTimerRef.current);
    hasAutoGeneratedRef.current = false;
    onClose();
  };

  if (!isOpen) return null;

  const generating = isGenerating || localGenerating;

  return (
    <div className="fixed inset-0 bg-gray-900/40 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <Send className="h-6 w-6 text-indigo-600" />
            <div>
              <h2 className="text-xl font-semibold text-gray-900">
                Offer Letter Request Email
              </h2>
              <p className="text-sm text-gray-500">
                Application #{applicationId}
              </p>
            </div>
          </div>
          
          <button
            onClick={handleClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        {/* Error Display */}
        {error && (
          <div className="mx-6 mt-4 p-3 bg-red-50 border border-red-200 rounded-lg flex items-center space-x-2">
            <AlertCircle className="h-4 w-4 text-red-500 flex-shrink-0" />
            <p className="text-sm text-red-600">{error}</p>
          </div>
        )}

        {/* Toolbar */}
        <div className="flex items-center justify-between p-4 border-b border-gray-100 bg-gray-50">
          <div className="flex items-center space-x-3">
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex items-center space-x-2 px-3 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {generating ? (
                <RefreshCw className="h-4 w-4 animate-spin" />
              ) : (
                <RefreshCw className="h-4 w-4" />
              )}
              <span>{generating ? 'Generating...' : 'Generate'}</span>
            </button>

            <div className="h-4 w-px bg-gray-300"></div>

            <button
              onClick={handleCopyToClipboard}
              disabled={!emailContent.trim()}
              className="flex items-center space-x-2 px-3 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 disabled:opacity-50 transition-colors"
            >
              {copySuccess ? (
                <CheckCircle className="h-4 w-4" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              <span>{copySuccess ? 'Copied!' : 'Copy'}</span>
            </button>
          </div>

          <div className="flex items-center space-x-4 text-sm text-gray-500">
            <div className="flex items-center space-x-1">
              <FileText className="h-4 w-4" />
              <span>{wordCount} words</span>
            </div>
            
            {hasUnsavedChanges && (
              <div className="flex items-center space-x-1 text-orange-600">
                <Clock className="h-4 w-4" />
                <span>Unsaved changes</span>
              </div>
            )}
          </div>
        </div>

        {/* Email Content Editor */}
        <div className="flex-1 p-6 overflow-hidden">
          <div className="h-full">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Email Content
            </label>
            <textarea
              value={emailContent}
              onChange={handleEmailChange}
              placeholder="Email content will appear here after generation..."
              className="w-full h-full min-h-[400px] p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent resize-none font-mono text-sm leading-relaxed"
              style={{
                fontFamily: '"SF Mono", "Monaco", "Inconsolata", "Roboto Mono", monospace'
              }}
              disabled={generating && typingInProgress}
            />
            {generating && (
              <div className="mt-2 text-xs text-gray-500">Generating draft…</div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t border-gray-200 bg-gray-50">
          <div className="text-sm text-gray-500">
            {emailContent ? (
              <span>Ready to save and use this email draft</span>
            ) : (
              <span>Generate an email draft to get started</span>
            )}
          </div>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleClose}
              className="px-4 py-2 text-gray-600 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            
            <button
              onClick={handleSave}
              disabled={!emailContent.trim() || isSaving || generating}
              className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              {isSaving ? (
                <RefreshCw className="h-4 w-4 animate-spin" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              <span>{isSaving ? 'Saving...' : saveButtonLabel}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
